auth/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.views.decorators.csrf import csrf_exempt as ce
from django.views.generic import TemplateView
from auth.views import (
    LoginModal,
    Login,
    Logout,
    Register,
    ChangePassword,
    Qaptcha,
    FeedbackRequest,
    DoRestore,
    RestorePassword
)

urlpatterns = patterns('',
    url(r'^login-modal/$', LoginModal.as_view(), name='login_modal'),
    url(
        r'^restore-password/$',
        TemplateView.as_view(template_name='auth/_restore_password.html'),
        name='restore_password_page'
    ),
    url(
        r'^register-modal/$',
        TemplateView.as_view(template_name='auth/_register_modal.html'),
        name='register_modal'
    ),
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', Logout.as_view(), name='logout'),
    url(r'^register/$', Register.as_view(), name='register'),
    url(r'^change-password/$', ChangePassword.as_view(), name='change_password'),
    url(r'^get-qaptcha/$', ce(Qaptcha.as_view()), name='get_qaptcha'),
    url(r'^request/$', ce(FeedbackRequest.as_view()), name='feedback_request'),
    url(r'^restore/$', ce(RestorePassword.as_view()), name='restore_password'),
    url(r'^dorestore/(?P<hash>[0-9a-f]+)/(?P<timestamp>[0-9]+)/(?P<user_id>[0-9]+)/$', DoRestore.as_view(), name='do_restore_password'),
)

conf/urls.py
from django.conf.urls import patterns, include, url
from content.views import (
    Index,
    StaticPage,
    NewsList,
    NewsView,
    ArticlesList,
    ArticleView,
    Custom404)
from search.views import Search
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^ulogin/', include('django_ulogin.urls')),
    url(r'^news/$', NewsList.as_view(), name='news_list'),
    url(r'^news/(?P<identity>.*)/$', NewsView.as_view(), name='news_view'),
    url(r'^articles/$', ArticlesList.as_view(), name='articles_list'),
    url(r'^articles/category/(?P<identity>.*)/$', ArticlesList.as_view(), name='articles_category'),
    url(r'^articles/(?P<identity>.*)/$', ArticleView.as_view(), name='article_view'),
    url(r'^advert/', include('advert.urls', namespace='advert')),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^user/', include('auth.urls', namespace='user')),
    url(r'^404/$', Custom404.as_view(), name='404'),
    url(r'^$', Index.as_view(), name='index'),
    url(r'^search/$', Search.as_view(), name='search'),

    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'(?P<slug>.*)/?$', StaticPage.as_view(), name='static_page'),

)

handler404 = 'content.views.handler404'

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% extends "bootstrap.html" %}
{% load common %}

{% block visible_data %}
		<header>
            {% include 'content/_top_banners.html' %}
			<div class="header clearfix">
				<div class="logo"><a {% if not vertical == 'index' %}href="/"{% endif %}><img src="/static/img/logo.gif" alt=""></a></div>
				<div class="slogan">
					{% partial 'top_company_teaser' %}
				</div>
				<div class="add-company">
                    <a href={% if lk_url %}"{{ lk_url }}"{% else %}"#login" rel="modal"{% endif %}>
                        Добавить компанию<br>в каталог
                    </a>
                </div>
				<div class="login">
                    {% if current_user %}
                    <p><a href="{{ lk_url }}">Личный кабинет</a></p>
					<p><a href="{% url 'auth:logout' %}">выход</a></p>
                    {% else %}
					<p><a id="login-modal-link" href="/auth/login-modal/" mw="600">Вход</a></p>
					<p><a id="reg-modal-link" href="/auth/register-modal/" mw="400">регистрация</a></p>
                    {% endif %}
				</div>
			</div>
			<div class="block-search clearfix">
				<span>Поиск</span>
                <form action="{% url 'search' %}">
				<input type="text" name="q" value="{{ request.GET.q|default:'' }}" placeholder="Например: Поклейка обоев">
				<button type="submit"><i></i></button>
                </form>
			</div>
			<div class="menu-block clearfix">
				<div class="item">
					<a class="link js-catalog" href="#">Услуги<br> компаний</a>
					{% include 'content/_services_menu.html' %}
				</div>
				<div class="item">
					<a class="link" href="{% url 'static_page' 'arenda-spectehniki' %}">Аренда<br> спецтехники</a>
				</div>
				<div class="item">
					<a class="link" href="{% url 'static_page' 'magazin-elektro-instrumentov' %}">Магазин электро-<br> инструментов</a>
				</div>
				<div class="item">
					<a class="link" href="{% url 'news_list' %}">Новости</a>
				</div>
				<div class="item">
					<a class="link" href="{% url 'articles_list' %}">Статьи</a>
				</div>
			</div>
		</header>
		<div class="page-block">
        {% block content %}{% endblock %}
        </div>
		<footer>
			<div class="footer">
				<div class="clearfix">
					<div class="logo"><a href="http://askremont.ru/media/ugc/2014/03/07/setka.jpg" class="fancybox"><img src="/static/img/logo-footer.gif" alt=""></a></div>
					<nav>
						<div class="menu">
							<ul class="clearfix">
								<li><a href="{% url 'news_list' %}">Новости</a></li>
								<li><a href="{% url 'articles_list' %}">Статьи</a></li>
								<li><a href="{% url 'static_page' 'reklama' %}">Реклама на сайте</a></li>
							</ul>
						</div>
					</nav>
					<div class="dev"><a href="http://www.crtweb.ru" target="_blank"><img src="/static/img/crtweb.gif" alt=""></a></div>
					<div class="social">
                        <div class="pluso" data-background="transparent" data-options="big,round,line,horizontal,counter,theme=04" data-services="vkontakte,facebook,twitter"></div>
					</div>
				</div>
			</div>
            {% partial 'counters' %}
		</footer>

{% endblock %}

templates/bootstrap.html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="title" content="{{ seo_data.title }}">
        <meta name="description" content="{{ seo_data.description }}">
        <meta name="keywords" content="{{ seo_data.keywords }}">
        <title>{{ seo_data.title }}</title>
		<meta name="viewport" content="width=device-width">

		<link rel="stylesheet" href="/static/css/normalize.css">
		<link rel="stylesheet" href="/static/css/main.css?v=2">
		<link rel="stylesheet" href="/static/css/overrides.css?v=2">
		<link rel="stylesheet" href="/static/css/jquery.fancybox.css">
		<link rel="stylesheet" href="/static/css/validationEngine.jquery.css?v=2">
		<script src="/static/js/vendor/modernizr-2.6.2.min.js"></script>
        {% block additional_styles %}{% endblock %}

		<!--[if lte IE 8]>
			<link rel="stylesheet" href="/static/css/ie.css">
		<![endif]-->

	</head>
	<body>
        {% block visible_data %}{% endblock %}
        {% block post_footer %}{% endblock %}
		<script src="/static/js/vendor/jquery-1.9.1.min.js"></script>
        <script src="/static/js/vendor/jquery-ui-1.10.3.custom.min.js"></script>
        <script src="/static/js/vendor/jquery.carouFredSel-6.2.1-packed.js"></script>
        <script src="/static/js/vendor/jquery.query-object.js"></script>
        <script src="/static/js/vendor/jquery.leanModal.min.js"></script>
        <script src="/static/js/vendor/jquery.validationEngine-ru.js"></script>
        <script src="/static/js/vendor/jquery.validationEngine.js"></script>
        <script src="/static/js/vendor/masonry.pkgd.min.js"></script>
        <script src="/static/js/vendor/jquery.fancybox.js"></script>
		<script src="/static/js/plugins.js"></script>
		<script src="/static/js/main.js?v=3"></script>
		<script src="/static/js/auth.js?v=3"></script>
        {% block additional_js %}{% endblock %}
        <script src="http://share.pluso.ru/pluso-like.js" defer="defer"></script>
        <!--[if (gte IE 6)&(lte IE 8)]>
			<script type="text/javascript" src="/static/js/vendor/selectivizr-min.js"></script>
		<![endif]-->
	</body>
</html>

templates/empty.html
{{ content_item.text|safe }}