auth/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.views.decorators.csrf import csrf_exempt as ce
from django.views.generic import TemplateView
from auth.views import (
    LoginModal,
    Login,
    Logout,
    Register,
    ChangePassword,
    Qaptcha,
    FeedbackRequest,
    DoRestore,
    RestorePassword
)

urlpatterns = patterns('',
    url(r'^login-modal/$', LoginModal.as_view(), name='login_modal'),
    url(
        r'^restore-password/$',
        TemplateView.as_view(template_name='auth/_restore_password.html'),
        name='restore_password_page'
    ),
    url(
        r'^register-modal/$',
        TemplateView.as_view(template_name='auth/_register_modal.html'),
        name='register_modal'
    ),
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', Logout.as_view(), name='logout'),
    url(r'^register/$', Register.as_view(), name='register'),
    url(r'^change-password/$', ChangePassword.as_view(), name='change_password'),
    url(r'^get-qaptcha/$', ce(Qaptcha.as_view()), name='get_qaptcha'),
    url(r'^request/$', ce(FeedbackRequest.as_view()), name='feedback_request'),
    url(r'^restore/$', ce(RestorePassword.as_view()), name='restore_password'),
    url(r'^dorestore/(?P<hash>[0-9a-f]+)/(?P<timestamp>[0-9]+)/(?P<user_id>[0-9]+)/$', DoRestore.as_view(), name='do_restore_password'),
)

catalog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from catalog.views import (
    CompanyView,
    CategoryView,
    TagView,
    UploadFile,
    CreateCompanyView,
    UpdateCompanyView,
    JsTreeCategories
)

urlpatterns = patterns('catalog.views',

    url(r'^company/edit/(?P<pk>[0-9]+)/$', UpdateCompanyView.as_view(), name='company_edit'),
    url(r'^company/new/$', CreateCompanyView.as_view(), name='company_add'),
    url(r'^company/upload_file/$', UploadFile.as_view(), name='company_upload_file'),
    url(r'^company/(?P<identity>.*)/$', CompanyView.as_view(), name='company_view'),
    url(r'^tag/(?P<tag>.*)/$', TagView.as_view(), name='tag_view'),
    url(r'^get_categories/(?P<company_id>[0-9]+)/$', JsTreeCategories.as_view(), name='get_categories'),
    url(r'^(?P<identity>.*)/$', CategoryView.as_view(), name='category'),
)

conf/urls.py
from django.conf.urls import patterns, include, url
from content.views import (
    Index,
    StaticPage,
    NewsList,
    NewsView,
    ArticlesList,
    ArticleView,
    Custom404)
from search.views import Search
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^ulogin/', include('django_ulogin.urls')),
    url(r'^news/$', NewsList.as_view(), name='news_list'),
    url(r'^news/(?P<identity>.*)/$', NewsView.as_view(), name='news_view'),
    url(r'^articles/$', ArticlesList.as_view(), name='articles_list'),
    url(r'^articles/category/(?P<identity>.*)/$', ArticlesList.as_view(), name='articles_category'),
    url(r'^articles/(?P<identity>.*)/$', ArticleView.as_view(), name='article_view'),
    url(r'^advert/', include('advert.urls', namespace='advert')),
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^user/', include('auth.urls', namespace='user')),
    url(r'^404/$', Custom404.as_view(), name='404'),
    url(r'^$', Index.as_view(), name='index'),
    url(r'^search/$', Search.as_view(), name='search'),

    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'(?P<slug>.*)/?$', StaticPage.as_view(), name='static_page'),

)

handler404 = 'content.views.handler404'

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

catalog/models.py
# -*- coding: utf-8 -*-
import random
from django.core.urlresolvers import reverse
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from common.shortcuts import upload_path_constructor
from common.models import BaseModel, CommonModelMixins
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator


class City(models.Model):
    title = models.CharField(
        verbose_name=u'Название',
        max_length=255,
    )

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'Город'
        verbose_name_plural = u'Города'


class Tag(BaseModel):
    '''
    Теги компаний
    '''
    title = models.CharField(
        verbose_name = u'Название',
        max_length=255,
    )

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'Тег'
        verbose_name_plural = u'Теги'


class Category(MPTTModel, CommonModelMixins):
    '''
    Категория компаний
    '''
    title = models.CharField(
        verbose_name=u'Название',
        max_length=255,
    )
    slug = models.SlugField(
        verbose_name=u'SEO URL',
        blank=True, null=True,
    )
    parent = TreeForeignKey(
        'self',
        verbose_name=u'Родительская категория',
        related_name='children',
        blank=True, null=True,
    )
    description = models.TextField(
        verbose_name=u'Краткое описание',
        help_text=u'Обязательно если категория будет показываться на главной',
        null=True, blank=True,
    )
    sort_pos = models.IntegerField(
        verbose_name=u'Порядок сортировки',
        default=0,
    )
    show_on_main = models.BooleanField(
        verbose_name=u'Показывать на главной',
        default=False
    )
    promo_block = models.TextField(
        verbose_name=u'Боковой промо блок',
        blank=True, null=True,
    )


    @property
    def link(self):
        return reverse('catalog:category', kwargs={'identity': self.slug or self.pk})


    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'

    class MPTTMeta:
        order_insertion_by = ['title']


COMPANY_STATUS_CHOICES = (
    ('active', u'Активная'),
    ('off', u'Отключена'),
    ('wantscheck', u'Требует проверки')
)


class Company(BaseModel):
    title = models.CharField(
        verbose_name=u'Название',
        max_length=255,
    )
    slug = models.SlugField(
        verbose_name=u'SEO URL',
        blank=True, null=True,
    )
    logo = models.ImageField(
        upload_to=upload_path_constructor,
        verbose_name=u'Логотип',
        null=True, blank=True
    )
    owner = models.ForeignKey(
        User,
        verbose_name=u'Владелец',
        null=True, blank=True,
    )
    description = models.TextField(
        verbose_name=u'Полное описание',
        blank=True, null=True,
    )
    slogan = models.TextField(
        verbose_name=u'Слоган',
        blank=True, null=True,
    )
    categories = TreeManyToManyField(
        Category,
        verbose_name=u'Сферы деятельности',
    )
    city = models.ForeignKey(
        City,
        verbose_name=u'Город',
        null=True, blank=True,
    )
    address = models.TextField(
        verbose_name=u'Адрес',
        null=True, blank=True,
    )
    site = models.CharField(
        max_length=200,
        verbose_name=u'Сайт',
        null=True, blank=True,
    )
    email = models.CharField(
        max_length=200,
        verbose_name=u'E-mail'
    )
    phones = models.CharField(
        max_length=200,
        verbose_name=u'Телефоны',
        null=True, blank=True,
    )
    contact_person = models.CharField(
        max_length=200,
        verbose_name=u'Контактное лицо',
        null=True, blank=True,
    )
    status = models.CharField(
        verbose_name=u'Статус',
        max_length=20,
        choices=COMPANY_STATUS_CHOICES,
        default='active',
    )
    price_min = models.IntegerField(
        verbose_name=u'Минимальная цена услуг',
        null=True, blank=True,
    )
    price_max = models.IntegerField(
        verbose_name=u'Максимальная цена услуг',
        null=True, blank=True,
    )
    show_on_main = models.BooleanField(
        verbose_name=u'Показывать на главной',
        default=False,
    )
    tags = models.ManyToManyField(
        Tag,
        verbose_name=u'Теги',
        null=True, blank=True,
    )

    @property
    def prices_range(self):
        if self.price_min and self.price_max:
            return u'%s - %s' % (self.price_min, self.price_max)
        if self.price_min:
            return u'от %s' % self.price_min
        if self.price_max:
            return u'до %s' % self.price_max
        return u''

    def __unicode__(self):
        return self.title

    @property
    def link(self):
        if self.slug and self.slug.strip():
            slug = self.slug.strip()
        else:
            slug = self.pk
        return u'/catalog/company/%s/' % slug

    def get_absolute_url(self):
        return self.link

    def random_worksets(self):
        sets = list(self.worksample_set.all())
        random.shuffle(sets)
        return sets[0:4]

    class Meta:
        verbose_name = u'Компания'
        verbose_name_plural = u'Компании'


class Service(BaseModel):
    company = models.ForeignKey(
        Company,
        verbose_name=u'Компания',
    )
    title = models.CharField(
        verbose_name=u'Название',
        max_length=255,
    )
    description = models.TextField(
        verbose_name=u'Полное описание',
        validators=[MaxLengthValidator(80)],
        blank=True, null=True,
    )
    cost_type = models.CharField(
        verbose_name=u'Тип стоимости',
        default='individual',
        max_length=50,
        choices=(
            ('individual', u'Индивидуальный расчет'),
            ('fixed', u'Фиксированная стоимость')
        )
    )
    cost = models.IntegerField(
        verbose_name=u'Стоимость',
        default=None,
        null=True, blank=True,
    )

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u'Услуга компании'
        verbose_name_plural = u'Услуги компаний'


class WorkSample(BaseModel):
    company = models.ForeignKey(
        Company,
        verbose_name=u'Компания',
    )
    image = models.ImageField(
        upload_to=upload_path_constructor,
        verbose_name=u'Фото',
        null=True, blank=True
    )
    cost = models.CharField(
        verbose_name=u'Стоимость',
        max_length=255,
        default=None,
        null=True, blank=True,
    )
    description = models.TextField(
        verbose_name=u'Краткое описание',
    )

    def __unicode__(self):
        return self.description

    class Meta:
        verbose_name = u'Пример работы компании'
        verbose_name_plural = u'Примеры работ компаний'

catalog/views.py
# -*- coding: utf-8 -*-
from django.forms.models import modelformset_factory
from django.http import Http404
from digg_paginator import DiggPaginator
from django.db.models import Q

from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView
from extra_views.advanced import CreateWithInlinesView
from catalog.forms import CompanyForm, ServiceForm, WorkSampleForm
from common.shortcuts import force_int, get_object_or_none
from common.views.generic import CommonAjaxUploadView, LoginRequiredMixin, JsonView
from content.models import Content
from catalog.models import Company, Category, Tag, Service, WorkSample
from extra_views import InlineFormSet, UpdateWithInlinesView


class CompanyView(TemplateView):
    '''
    Просмотр компании
    '''
    template_name = 'catalog/company_view.html'
    ctx_name = 'company'

    def get_context_data(self, **kwargs):
        ctx = super(CompanyView, self).get_context_data(**kwargs)
        nid = self.kwargs.get('identity')
        pk_filter = Q(slug=nid)
        try:
            pk_filter = Q(pk=int(nid))
        except:
            pass

        status_filter = Q(status='active')
        u = self.request.user
        if u.is_authenticated():
            status_filter |= Q(Q(status='wantscheck') & Q(owner=u))

        try:
            company = Company.objects.get(
                pk_filter,
                status_filter
            )
        except Company.DoesNotExist:
            raise Http404(u'Компания не найдена')


        #company.inc('views_count')

        ctx.update({
            self.ctx_name: company,
            'seo_data': company.seo_data,
            'vertical': 'catalog'
        })
        return ctx


def shared_queryset_modifier(qs, request):
        order = request.GET.get('price_order', 'desc')
        if order in ['asc', 'desc']:
            qs = qs.order_by('price_min' if order == 'asc' else '-price_min')

        price_min = force_int(request.GET.get('price_min', '0'))
        if price_min:
            qs = qs.filter(price_min__gte=price_min)

        price_max = force_int(request.GET.get('price_max', '0'))
        if price_max and price_max >= price_min:
            qs = qs.filter(price_max__lte=price_max)
        return qs


class CategoryView(ListView):
    template_name = 'catalog/subcategory.html'
    context_object_name = 'companies'
    model = Company
    paginator_class = DiggPaginator
    paginate_by = 5

    def get_queryset(self):
        category = Category.get_by_identity(self.kwargs.get('identity'))
        self.category = category
        self.subcategories = list(category.get_children())
        qs = super(CategoryView, self).get_queryset()
        qs = qs.prefetch_related('worksample_set').filter(categories__in=[category])
        return shared_queryset_modifier(qs, self.request)

    def get_context_data(self, **kwargs):
        ctx = super(CategoryView, self).get_context_data(**kwargs)
        ctx['category'] = self.category
        if self.subcategories:
            ctx['subcategories'] = self.subcategories
            self.template_name = 'catalog/category.html'
        ctx['seo_data'] = self.category.seo_data
        ctx['vertical'] = 'catalog'
        ctx['tag_name'] = ''
        return ctx


class TagView(ListView):
    template_name = 'catalog/subcategory.html'
    context_object_name = 'companies'
    paginator_class = DiggPaginator
    paginate_by = 5
    model = Tag

    def get_queryset(self):
        ctx = super(TagView, self).get_queryset()
        tag_name = self.kwargs.get('tag')
        self.tag = get_object_or_404(Tag, title=tag_name)
        qs = self.tag.company_set.prefetch_related('worksample_set', 'categories')
        return shared_queryset_modifier(qs, self.request)

    def get_context_data(self, **kwargs):
        ctx = super(TagView, self).get_context_data(**kwargs)
        tag_name = self.kwargs.get('tag')
        ctx['seo_data'] = self.tag.seo_data
        ctx['vertical'] = 'catalog'
        ctx['tag_name'] = tag_name
        return ctx


class ServiceInline(InlineFormSet):
    model = Service
    extra = 1


class WorkSampleInline(InlineFormSet):
    model = WorkSample
    extra = 1
    form_class = WorkSampleForm


class CreateCompanyView(CreateWithInlinesView):
    template_name = 'catalog/company_edit.html'
    model = Company
    form_class = CompanyForm

    def get_inlines(self):
        s = ServiceInline
        s.extra = 2
        w = WorkSampleInline
        w.extra = 2
        return [s, w]

    def get_form_class(self):
        cls = CompanyForm
        cls.user = self.request.user
        return cls


class UpdateCompanyView(UpdateWithInlinesView):
    template_name = 'catalog/company_edit.html'
    model = Company
    inlines = [ServiceInline, WorkSampleInline]

    def get_form_class(self):
        cls = CompanyForm
        cls.user = self.request.user
        return cls


class UploadFile(LoginRequiredMixin, CommonAjaxUploadView):
    model_name = 'company_images'
    thumb_size = '200x200'

    def preprocess(self):
        self.thumb_size = self.request.POST.get('thumb_size') or self.thumb_size
        ret = super(UploadFile, self).preprocess()
        fname = ret.get('fname')
        if fname:
            ret['fname'] = fname
        return ret

    def get_rel_path(self):
        return self.model_name

    def apply_to_model(self, fname):
        return True

from mptt.templatetags.mptt_tags import cache_tree_children

class JsTreeCategories(JsonView):
    def preprocess(self):
        ret = []
        data = list(Category.objects.filter(parent__isnull=True))

        self.selected_ids = [];
        company = get_object_or_none(Company, pk=self.kwargs.get('company_id'))
        if company:
            self.selected_ids = company.categories.values_list('pk', flat=True)

        for c in data:
            ret.append(
                self.recursive_node_to_dict(c)
            )

        return ret

    def recursive_node_to_dict(self, node):
        result = {
            'id': node.pk,
            'label': node.title,
            'checkbox': False,
        }
        children = [self.recursive_node_to_dict(c) for c in node.get_children()]
        if children:
            result['branch'] = children
        else:
            result['checkbox'] = True
            if node.pk in self.selected_ids:
                result['checked'] = True
        return result

templates/catalog/_company_map.html
<div class="modal" id="cont-map">
    <div class="title clearfix">
        <span>Адрес компании</span>
        <div class="modal-add">
            {{ company.address }}
            <a href="javascript:void(0);" class="close-modal" style="padding:0px; margin-top:0;"></a>
        </div>
    </div>
    <div id="map"></div>
</div>

templates/catalog/category.html
{% extends 'base.html' %}
{% load banners pytils_dt thumbnail mptt_tags  %}

{% block content %}
<div class="main-block clearfix">
        <div class="right-side">
                {% advert 'catalog' 'sidebar' %}
        </div>
        <div class="left-big-block">
                <ul class="breadcrumbs" style="min-height:20px;">
                        <li class="main"><a href="/">Главная</a></li>
                        <li>{{ category.title }}</li>
                </ul>
                <h1 class="block-header" style="text-align:left;margin-left: 0;">{{ category.title }}</h1>
                <ul class="services-list clearfix">
                {% for cat in subcategories %}
                        <li><a href="{{ cat.link }}">{{ cat.title }}</a></li>
                {% endfor %}
                </ul>
        </div>
</div>

{% if seo_data.visible_text %}
<div class="clear"></div>
<div class="just-text seo-visible" style="margin-left:0px;">
    <p>{{ seo_data.visible_text|safe }}</p>
</div>
{% endif %}
<div class="clear"></div>

<div class="big-banner clearfix">
    <div class="item">{% advert 'catalog' 'bottom_1' %}</div>
    <div class="item">{% advert 'catalog' 'bottom_2' %}</div>
</div>
{% endblock %}

templates/catalog/company_edit.html
{% extends 'base.html' %}
{% load thumbnail mptt_tags  %}
{% load widget_tweaks %}

{% block additional_styles %}
<link rel="stylesheet" href="/static/css/jquery.formstyler.css?v=2">
<link rel="stylesheet" href="/static/css/company_edit.css?v=2">
<link rel="stylesheet" href="/static/js/vendor/acitree/css/aciTree.css">
{% endblock %}

{% block additional_js %}
<script src="/static/js/vendor/plupload/i18n/ru.js"></script>
<script src="/static/js/vendor/plupload/plupload.min.js"></script>
<script src="/static/js/askuploader.js"></script>
<script src="/static/js/vendor/acitree/js/jquery.aciPlugin.min.js"></script>
<script src="/static/js/vendor/acitree/js/jquery.aciTree.core.js"></script>
<script src="/static/js/vendor/acitree/js/jquery.aciTree.selectable.js"></script>
<script src="/static/js/vendor/acitree/js/jquery.aciTree.checkbox.js"></script>
<script src="/static/js/company_edit.js?v=2"></script>
{% endblock %}

{% block content %}
<div class="block-private">
    <div class="block-title">
        <p>Личный кабинет</p>
    </div>
    <div id="tabs">
        <ul class="tabs clearfix">
            <li class="ui-tabs-active"><a href="#private">Редактировать информацию о компании</a></li>
            <li><a href="{% url 'user:change_password' %}">Изменить пароль</a></li>
        </ul>
        <div class="block" id="private">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.owner }}
                {{ form.status }}
                {% if form.errors %}
                <h3 style="color:red;">Форма содержит ошибки! Не удалось сохранить компанию.</h3>
                {% endif %}
                <div class="selected logotype">
                    <h3>Логотип компании</h3>
                    <div class="clearfix">
                        <div class="img" id="logo-cont">
                            {% thumbnail form.instance.logo "200x200" as im %}
                            <img src="{{ im.url }}" alt="">
                            {% empty %}
                            <span>Логотип компании</span>
                            <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" alt="">
                            {% endthumbnail %}
                        </div>
                        <div class="red">{{ form.logo.errors }}</div>
                        <div class="add-logo" data-upload-url="{% url 'catalog:company_upload_file' %}" id="add-logo-cnt">
                            {{ form.logo }}
                            <a href="#" id="add-logo-btn">{% if form.instance.logo %}Заменить{% else %}Добавить{% endif %} логотип</a>
                        </div>
                    </div>
                </div>
                <div class="selected info">
                    <h3>Общая информация</h3>
                    <ul>
                        <li>
                            <label>
                                Название компании:
                                <div class="red">{{ form.title.errors }}</div>
                            </label>
                            {{ form.title }}
                        </li>
                        <li>
                            <label>
                                Слоган компании:
                                <div class="red">{{ form.slogan.errors }}</div>
                            </label>
                            {{ form.slogan }}
                        </li>
                        <li>
                            <label>
                                Сферы деятельности:
                                <div class="red">{{ form.categories.errors }}</div>
                            </label>
                            {{ form.categories|add_class:"hidden" }}
                            <div id="categories-container" style="padding-left: 180px;margin: -20px 0 20px 0;" class="aciTree" data-url="{% url 'catalog:get_categories' form.instance.pk|default:'0' %}"></div>
                        </li>
                        <li>
                            <label>
                                О компании:
                                <div class="red">{{ form.description.errors }}</div>
                            </label>
                            {{ form.description|attr:"maxlength:540" }}
                            <p>Символов осталось: <span id="desc-symbols-count">540</span></p>
                        </li>
                    </ul>
                </div>
                <div class="selected contacts">
                    <h3>Контактная информация</h3>
                    <ul>
                        <li>
                            <label>
                                Укажите город:
                                <div class="red">{{ form.city.errors }}</div>
                            </label>
                            {{ form.city }}
                        </li>
                        <li>
                            <label for="">
                                Адрес:
                                <div class="red">{{ form.address.errors }}</div>
                            </label>
                            {{ form.address }}
                        </li>
                        <li>
                            <label for="">
                                Сайт компании:
                                <div class="red">{{ form.site.errors }}</div>
                            </label>
                            {{ form.site }}
                        </li>
                        <li>
                            <label for="">
                                E-mail:
                                <div class="red">{{ form.email.errors }}</div>
                            </label>
                            {{ form.email }}
                        </li>
                        <li>
                            <label for="">
                                Телефоны:
                                <div class="red">{{ form.phones.errors }}</div>
                            </label>
                            {{ form.phones }}
                        </li>
                        <li>
                            <label for="">
                                Контактное лицо:
                                <div class="red">{{ form.contact_person.errors }}</div>
                            </label>
                            {{ form.contact_person }}
                        </li>
                    </ul>
                </div>
                <div class="selected services formsets">
                    <h3>Информация об услугах</h3>
                    {% with services_formset=inlines.0 %}
                    {{ services_formset.management_form }}
                    {{ services_formset.non_field_errors }}
                    {% for service_form in services_formset %}
                    <div class="js-formset-item block-services" {% if forloop.last %}style="display:none;"{% endif %}>
                        <a href="javascript:void(0);" class="close js-remove-formset"></a>
                        {{ service_form.company }}
                        {{ service_form.id }}
                        <ul class="clearfix">
                            <li>
                                <label>
                                    Название услуги:
                                    <div class="red">{{ service_form.title.errors }}</div>
                                </label>
                                {{ service_form.title }}
                                <span style="display:none">{{ service_form.DELETE }}</span>
                            </li>
                            <li>
                                <label>
                                    Стоимость услуги:
                                    <div class="red">{{ service_form.cost.errors }}</div>
                                </label>
                                {{ service_form.cost_type|add_class:'serv-cost-type'|attr:'autocomplete:off' }}
                                <div class="serv-cost-val" {% if service_form.instance.cost_type = 'individual' or forloop.last %}style="display:none;"{% endif %}>
                                от {{ service_form.cost }} руб.
                                </div>
                            </li>
                            <li>
                                <label>
                                    Описание услуги:
                                    <div class="red">{{ service_form.description.errors }}</div>
                                </label>
                                {{ service_form.description }}
                            </li>
                        </ul>
                    </div>
                    {% endfor %}
                    {% endwith %}
                    <div class="button"><a href="#" class="js-add-formset-item">Добавить услуги</a></div>
                </div>
                <div class="selected work formsets">
                    <h3>Примеры работ компании</h3>
                    {% with worksamples_formset=inlines.1 %}
                    {{ worksamples_formset.management_form }}
                    {{ worksamples_formset.non_field_errors }}
                    {% for worksample_form in worksamples_formset %}
                    <div class="js-formset-item block-work" {% if forloop.last %}style="display:none;"{% endif %}>
                        <a href="#" class="close js-remove-formset">Удалить работу</a>
                        {{ worksample_form.company }}
                        {{ worksample_form.id }}
                        {{ worksample_form.DELETE|add_class:"hidden"|attr:"autocomplete:off" }}
                        <div class="clearfix">
                            <div class="img" id="work-img-{{ forloop.counter }}" {% if not worksample_form.instance.image %}style="background: #F9F9F9"{% endif %}>
                                {# worksample_form.images|add_class:"hidden"|attr:"autocomplete:off" #}
                                {% thumbnail worksample_form.instance.image "382x225" as im %}
                                <img src="{{ im.url }}" alt="">
                                {% empty %}
                                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" alt="">
                                {% endthumbnail %}
                                <a href="#" id="work-img-pick-{{ forloop.counter }}">
                                    {% if not worksample_form.instance.image %}Загрузить{%else %}Заменить{% endif %} картинку
                                </a>
                                {{ worksample_form.image }}
                            </div>
                            <div class="form">
                                <ul>
                                    <li>
                                        <label>
                                            Стоимость работ:
                                            <div class="red">{{ worksample_form.cost.errors }}</div>
                                        </label>
                                        {{ worksample_form.cost|attr:'autocomplete:off' }}
                                        <span>Наприме: "5000 рублей за проект"</span>
                                    </li>
                                    <li>
                                        <label>
                                            Краткое описание работы:
                                            <div class="red">{{ worksample_form.description.errors }}</div>
                                        </label>
                                        {{ worksample_form.description|attr:"maxlength:80"|attr:'autocomplete:off' }}
                                        <span>Не больше 80 символов</span>

                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endwith %}
                    <div class="button"><a href="#" class="js-add-formset-item">Добавить работы</a></div>
                </div>
                <div class="button-block clearfix">
                    <button name="domoderate" type="submit"><i></i>Сохранить изменения</button>
                    <input style="float:right; margin-right: 20px;" name="domoderate" type="submit" value="Отправить на модерацию">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/catalog/email_request_email.html
Пользователь представившийся как "{{ name }}" просит связаться с ним по электронной почте.<br>
E-mail: {{ email }}<br>
{% if text %}<br><br>
При отправке заявки пользоватеь оставил следующее сообщение:<br><br>
{{ text }}
{% endif %}